@host = https://localhost:7009

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "",
    "lastName": "Pitchai",
    "email":"santhanam@gmail.com",
    "password":"abcd@123",

    "startDateTime":"2023-12-25T04:00:00",
    "endDateTime":"2023-12-24T11:00:00",
    "roles": [
        "",
        "Developer",
        "Architect"
    ]
}

